Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    # aws.access_key_id = "ここに指定すると"
    # aws.secret_access_key = "危険です!!"

    aws.keypair_name = "v_schoo_vagrant"

    aws.region = "us-east-1"

    aws.ami = "ami-7747d01e"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/reoring/.ssh/v_schoo_vagrant.pem"
  end
end
