Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "v_schoo_vagrant"

    aws.region = "us-east-1"

    aws.ami = "ami-b1143ba7"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/reoring/.ssh/v_schoo_vagrant.pem"

    config.vm.provision "chef_zero" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.nodes_path = "nodes"
      chef.roles_path = "roles"

      chef.add_recipe "recipe[apache2]"
      chef.add_recipe "recipe[git]"
    end
  end
end
