# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.200.10"

  config.vm.provision "docker", images: ["ubuntu"]

  config.vm.provision "docker" do |d|
    d.run "php-apache",
      image: "php:7.0-apache",
      args: "-v '/vagrant/src:/var/www/html' -p 80:80"
  end
end
